import {
  Type,
  AlignLeft,
  Hash,
  Mail,
  Phone,
  Calendar,
  ChevronDown,
  ListChecks,
  CheckSquare,
  CircleDot,
  Star,
  SlidersHorizontal,
  FileText,
  MapPin,
  PenTool,
  Upload,
  Heading,
  Minus,
  Pilcrow,
  LucideIcon,
} from 'lucide-react';
import { FieldType } from '@/types/form';

export const FIELD_ICONS: Record<FieldType, LucideIcon> = {
  text: Type,
  textarea: AlignLeft,
  number: Hash,
  email: Mail,
  phone: Phone,
  date: Calendar,
  select: ChevronDown,
  'multi-select': ListChecks,
  checkbox: CheckSquare,
  radio: CircleDot,
  rating: Star,
  slider: SlidersHorizontal,
  richtext: FileText,
  address: MapPin,
  signature: PenTool,
  file: Upload,
  header: Heading,
  divider: Minus,
  content: Pilcrow,
};
